<?php # vim: set fenc=utf8 ts=4 sw=4:

class Response
{
	private $content;

	/**
	 */
	public function set_header ($header_name, $content)
	{
		header ($header_name.': '.$content);
	}

	/**
	 */
	public function set_content_type ($content_type)
	{
		# TODO
	}

	/**
	 */
	public function set_status ($status_code, $message)
	{
	}

	/**
	 */
	public function set_content ($content)
	{
		$this->content = $content;
	}

	/**
	 * \param	route_or_url
	 * 			Either route object generated by Router or URL string.
	 * 			If relative URL is given, it is relative to base-url of framework installation.
	 */
	public function redirect_to ($route_or_url)
	{
	}

	/**
	 */
	public function is_redirected()
	{
	}

	/**
	 * Returns response to User-Agent.
	 */
	public function answer()
	{
		# TODO set headers
		# TODO set status
		# TODO set ETag and check if we should respons Not-Modified or respond with full body.
		echo $this->content;
	}
}

?>
